#!/bin/bash

first_artist=""

	new_artist=`playerctl -i plasma-browser-integration metadata --format '{{ artist }}'`
	#new_artist=`playerctl -p tidal-hifi metadata --format '{{ artist }}'`
	#new_artist=`playerctl -p "$(playerctl -l | awk 'NR==3')" metadata --format '{{ artist }}'`
	#new_artist=`playerctl -p playerctld metadata --format '{{ artist }}'`
	if [ "$new_artist" != "$first_artist" ] 
	then
		first_artist="$new_artist"
		echo "$new_artist"
	fi
	sleep 1
