#!/bin/bash

first_album=""

	new_album=`playerctl -i plasma-browser-integration metadata --format '{{ album }}'`
	#new_album=`playerctl -p tidal-hifi metadata --format '{{ album }}'`
	#new_album=`playerctl -p "$(playerctl -l | awk 'NR==3')" metadata --format '{{ album }}'`
	#new_album=`playerctl -p playerctld metadata --format '{{ album }}'`
	if [ "$new_album" != "$first_album" ]
	then
		first_album="$new_album"
		echo "$new_album"
	fi
	sleep 1
