#!/bin/bash

first_album=""

	current_instance=`playerctl metadata -l | grep chromium.instance9`
	new_album=`playerctl metadata -p $current_instance --format '{{ album }}'`
	if [ "$new_album" != "$first_album" ]
	then
		first_album="$new_album"
		echo "$new_album"
	fi
	sleep 1
