#!/bin/bash

first_title=""

	current_instance=`playerctl metadata -l | grep chromium.instance9`
	new_title=`playerctl metadata -p $current_instance --format '{{ title }}'`
	if [ "$new_title" != "$first_title" ] 
	then
		first_title="$new_title"
		echo "$new_title"
	fi
	sleep 1

