#!/bin/bash

first_artist=""

	current_instance=`playerctl metadata -l | grep chromium.instance9`
	new_artist=`playerctl metadata -p $current_instance --format '{{ artist }}'`
	if [ "$new_artist" != "$first_artist" ] 
	then
		first_artist="$new_artist"
		echo "$new_artist"
	fi
	sleep 1
