#!/bin/bash

first_title=""

	#new_title=`playerctl metadata --format '{{ title }}'`
	new_title=`playerctl --player=wiimplay metadata --format '{{ trunc(title, 29) }}'`
	if [ "$new_title" != "$first_title" ] 
	then
		first_title="$new_title"
		echo "$new_title"
	fi
	sleep 1

