#!/bin/bash

first_album=""

	new_album=`playerctl --player=wiimplay metadata --format '{{ album }}'`
	if [ "$new_album" != "$first_album" ]
	then
		first_album="$new_album"
		echo "$new_album"
	fi
	sleep 1
